version: '3'

services:
  app:
    build:
      context: ./
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - '../live_py/:/app/'
    env_file:
      - ../.env
networks:
      - webserver-net

      
networks:
  webserver-net:
    external: true

