global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: postfix
    static_configs:
      - targets: ['172.17.0.1:9154']
  - job_name: dovecot
    static_configs:
      - targets: ['172.17.0.1:9093']
  - job_name: node
    static_configs:
      - targets: ['172.17.0.1:9094']
  - job_name: traefik
    static_configs:
      - targets: ['172.17.0.1:6032']
