version: '3.1'
services:
  web:
    image: odoo:latest
    depends_on:
      - mysql
    ports:
      - "8069:8069"
    env_file:
      - ./mariadb.env
    networks:
      - webserver-net
    
networks:
  webserver-net:
    external: true

