version: '3'

services:
  nginx:
    image: nginx:alpine
    #image: nginx:latest
    #restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${HOME}/certbot/conf:/etc/letsencrypt
      - ${HOME}/apache2:/etc/apache2
      - ${HOME}/certbot/www:/var/www/certbot
      - ${HOME}/lav/siti:/var/www/html/
      - ${HOME}/log:/var/log/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webserver-net

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${HOME}/certbot/conf:/etc/letsencrypt
      - ${HOME}/certbot/www:/var/www/certbot
      - ${HOME}/log/:/var/log/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - webserver-net

  php-app:
    build:
      context: php/
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - /var/www/html/:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - webserver-net

  mysql:
    #image: mysql
    image: mariadb
    restart: unless-stopped
    env_file:
      - mysql/mariadb.env
      #- mysql/database.env
    volumes:
      - ${HOME}/mysql-data:/var/lib/mysql
    networks:
      - webserver-net

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - '8080:80'
  #   restart: unless-stopped
  #   environment:
  #     PMA_HOST: mysql
  #   depends_on:
  #     - mysql
  #   networks:
  #     - webserver-net

networks:
  webserver-net:
    external: true

