name: Sample Python

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/[email protected]
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
    - name: Test with pytest
      run: |
        python3 -m pytest
